version: '3.5'

services:
    traefik:
        command: --docker.domain=${traefik_domain} --acme.email=${traefik_email} --logLevel=DEBUG
        volumes: 
            - ./traefik/traefik.prod.toml:/traefik.toml
        labels:
            - traefik.frontend.rule=Host:${traefik_url}
            - traefik.frontend.auth.basic=${traefik_auth}
            - ghosts.host=${traefik_url}
            - ghosts.auth=true

    ghosts:
        command: -nohosts -proxymode -webnavbgcolor "#ffffff" -webnavtextcolor "#50596c"
        labels: 
            - traefik.frontend.rule=Host:${ghosts_url}
            - traefik.frontend.auth.basic=${ghosts_auth}
            - ghosts.host=${ghosts_url}

    portainer:
        command: -H unix:///var/run/docker.sock
        labels:
            - traefik.frontend.rule=Host:${portainer_url}
            - ghosts.host=${portainer_url}

    adminer:
        labels: 
            - traefik.frontend.rule=Host:${adminer_url}
            - traefik.frontend.auth.basic=${adminer_auth}
            - ghosts.host=${adminer_url}
            - ghosts.auth=true

    mailhog:
        labels: 
            - traefik.frontend.rule=Host:${mailhog_url}
            - traefik.frontend.auth.basic=${mailhog_auth}
            - ghosts.host=${mailhog_url}
            - ghosts.auth=true